### ISSUE TITLE
Add support for Ruby 2.4.x

### ISSUE THREAD

**Issue by lucasmazza** [Dockbit/library#2]
I noticed that repos with a `.ruby-version` with `2.4.0` or `2.4.1` won't work as expected with images like` ruby` and `s3_website`. I believe the images need to be updated to include recent ruby releases.

**Comment by 0xAhmed** [comment]
Hey @lucasmazza 👋

Thanks a ton for reporting this.

As of today, versions `2.4.0`, `2.4.1` as well as the latest minor of `2.3` of the Ruby provider are available on Dockbit. This is also reflected on the `s3_website` Provider.

We'll be following a more regular update cycle from now on for not only the Ruby provider but the rest of the providers also.

Please let me know if that takes care of it, Thanks.

**Comment by lucasmazza** [comment]
@0xAhmed tested it with a fresh deployment and it works as expected - thanks!
